apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ksxbbrmc
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jsmid/go-ksxbbrmc:azure-744d6b1adeb32dad5cac1cae25da558485dbd444
        name: container-image  
